on:
  push:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  check-domain-names:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - run: bundle exec ruby available_names.rb
      - name: commit files
        run: |
          git config --local user.email "oliver@codeandclay.com"
          git config --local user.name "codeandclay"
          git add "available_sh_domains.json"
          git commit -m "Update available domains list" -a
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: trigger page build
        run: |
          curl -XPOST -H "Accept: application/vnd.github.v3+json" -u "codeandclay:${{secrets.ACCESS_TOKEN}}" \
          https://api.github.com/repos/codeandclay/goodi.sh-builder/actions/workflows/build_site.yml/dispatches \
          -d '{"ref":"refs/heads/main"}'
